name: hn_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  url_launcher: ^5.0.1

  json_annotation: ^2.0.0

  built_collection: '>=2.0.0 <4.0.0'

  built_value: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^2.0.0

  build_runner: ^1.0.0

  built_value_generator:
    git:
      url: https://github.com/efortuna/built_value.dart.git/
      path: built_value_generator


flutter:

  uses-material-design: true

